[[fonts]]
path = "resource/osaka-re.ttf"

[[textures]]
path = "resource/Player.png"

[[texts]]
path = "resource/text.txt"

[[animations]]
path = "resource/Player.png"
frames = [[0, 0, 200, 200], [200, 0, 200, 200], [400, 0, 200, 200], [200, 0, 200, 200]]